<a href="https://colab.research.google.com/github/nupursjsu/Deep-Learning/blob/master/Ungraded_Assignment5/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Demonstrating some basic tensorflow operations

## Importing required libraries

In [0]:
import tensorflow as tf

## Working with Tensors

Doing some basic tensor operations such as add, matmul, square, reduce_sum 

In [5]:
print(tf.add(3, 2))
print(tf.add([5, 8], [4, 5]))
print(tf.square(4))
print(tf.reduce_sum([4, 6, 3]))

#Demomnstrating Operator overloading
print(tf.square(4) + tf.square(7))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([ 9 13], shape=(2,), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(65, shape=(), dtype=int32)


In [7]:
a = tf.matmul([[1]], [[2, 3]])
print(a)
print(a.shape)
print(a.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


### Demonstrating NumPy Compatibility

In [8]:
import numpy as np

nd_array = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(nd_array, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


## Showing GPU acceleration

In [9]:
n = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(n.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU #0:  
False


### Explicit Device Placement

In [10]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

#Forcing execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

#Forcing execution on GPU #0 if available
if tf.config.experimental.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 383.81ms


## Demonstarting tf.data.Dataset API

In [0]:
#Creating a source dataset

tensor_dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

#Creating a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

dataset_file = tf.data.TextLineDataset(filename)

In [0]:
#Applying transformations
tensor_dataset = tensor_dataset.map(tf.square).shuffle(2).batch(2)

dataset_file = dataset_file.batch(2)

In [14]:
#Iterating over the records

print('Elements of tensor_dataset:')
for x in tensor_dataset:
  print(x)

print('\nElements in dataset_file:')
for x in dataset_file:
  print(x)

Elements of tensor_dataset:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16  4], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)

Elements in dataset_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
