<a href="https://colab.research.google.com/github/nupursjsu/Deep-Learning/blob/master/Ungraded_Assignment4/PyTorch_Basics_Chap1and2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals - Chapter 1 and 2

In [0]:
#importing necessary libraries
import torch

In [2]:
#Checking torch version
torch.version.__version__

'1.5.0+cu101'

In [18]:
#Creating a pyTorch tensor of size 4
a = torch.ones(4)
a

tensor([1., 1., 1., 1.])

In [20]:
#Accessing element using indices
a[1]

tensor(1.)

In [21]:
float(a[1])

1.0

In [22]:
#updating element in tensor
a[2] = 3
a

tensor([1., 1., 3., 1.])

In [32]:
#Passing a list of lists to constructor
p = torch.tensor([[6.0, 7.0], [4.0, 1.0], [9.0, 1.0]])
p

tensor([[6., 7.],
        [4., 1.],
        [9., 1.]])

In [33]:
#Checking size of tensor along each dimension
p.shape

torch.Size([3, 2])

In [34]:
#Acessing individual element of above tensor using two indices
p[0, 1]

tensor(7.)

In [35]:
#Accessing all the elements in a tensor using .storage property
p.storage()

 6.0
 7.0
 4.0
 1.0
 9.0
 1.0
[torch.FloatStorage of size 6]

In [36]:
#Shows the number of elements to be skipped in storage along each dimension
p.stride()

(2, 1)

In [39]:
#Transposing a tensor
p_t = p.t()
p_t

tensor([[6., 4., 9.],
        [7., 1., 1.]])

In [40]:
#Checking if two tensor and its transpose share same storage
id(p.storage()) == id(p_t.storage())

True

In [44]:
#Allocating the datatype we want to a tensor by passing it in the constructor
data_p = torch.ones(4, 2, dtype=torch.double)
data_p

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [45]:
data_p.dtype

torch.float64

In [46]:
#Getting a numpy array out of your tensor
p = torch.ones(3, 4)
p_numpy = p.numpy()
p_numpy

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
a = torch.ones(4,4)
b = torch.ones(4,4)

In [4]:
#Adding two tensors
a + b

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [5]:
#Moving tensors to GPU
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], device='cuda:0')